// STEP-2 DESIGN THE TYPES OF ACTIONS THE STATE MIGHT SUFFER
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const RESET_INPUTS = 'RESET_INPUTS'
//fetching smurfs
export const GET_SMURFS = 'GET_SMURFS';
export const GET_SMURFS_SUCCESS = 'Get_SMURFS_SUCCESS';
export const GET_SMURFS_FAIL = "GET_SMURFS_FAIL"
// creating new smurfs
export const POST_SMURFS ='POST_SMURFS'
export const POST_SMURFS_SUCCESS = 'POST_SMURFS_SUCESS';
export const POST_SMURFS_FAILURE = 'POST_SMURFS_FAILURE'
